extends: default

rules:
  document-start: disable
  document-end: disable
  line-length:
    max: 120
    level: warning
  indentation:
    spaces: 2
    indent-sequences: true
  comments:
    min-spaces-from-content: 2
  comments-indentation: disable
  truthy:
    allowed-values: ['true', 'false', 'on', 'off']
  brackets:
    min-spaces-inside: 0
    max-spaces-inside: 1
  braces:
    min-spaces-inside: 0
    max-spaces-inside: 1
    min-spaces-inside-empty: 0
    max-spaces-inside-empty: 0
  colons:
    max-spaces-before: 0
    max-spaces-after: 1
  commas:
    max-spaces-before: 0
    max-spaces-after: 1
  hyphens:
    max-spaces-after: 1
  key-duplicates: enable
  new-line-at-end-of-file: enable
  trailing-spaces: enable
  empty-lines:
    max: 2
    max-start: 0
    max-end: 1

ignore: |
  .github/
  node_modules/
  vendor/
  dist/
  build/
